# # #
# https://gohugo.io
# https://gohugo.io/getting-started/configuration
# https://www.mikedane.com/static-site-generators/hugo/
# # #

#baseURL         = "http://dev.localhost/Nextcloud/NextPublic/HUGO/HugoPortfolio/public/"
languageCode    = "fr-FR"

baseURL         = "https://thierrycharriot.netlify.app/"
footnoteReturnLinkContents = "↩"
title           = "Portfolio"

theme           = "HugoPortfolioTheme"  
contentdir      = "content"
publishdir      = "public"
paginate        = 3
enableRobotsTXT = true

googleAnalytics = "UA-152719063-2"

[params]
  AuthorName    = "Thierry Charriot"
  GitHubUser    = "bibibricodeur"
  #SidebarRecentLimit = 3
  #Subtitle      = ""
  
  # metas
  author        = "Thierry Charriot"
  description   = "Intégrateur, intégrations sites statiques, sites vitrines, WordPress, Hugo 17160 Matha, Saintonge, Charente-Maritime"
  # ajouter apropos
  adresse       = "17160 Matha"
  courriel      = "bibibricodeur(signe bizarre)gmail.com"   
  hebergement   = "https://www.netlify.com/"
  hebergeur     = "Netlify"
  proprietaire  = "Thierry Charriot"    
  statut        = "particulier"
  telephone     = "+33 638019097"

[permalinks]
  posts         = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    identifier  = "mentions"
    name        = "Mentions légales"
    pre         = ""
    url         = "mentions"
    weight      = 1

### Fin

